### ISSUE TITLE
cannot create domain if same domain is used by another installation

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#1]
Not sure if this is by design, but I can't create a domain on an install if that domain is already in use by another install. IE I created "mydomain.com" on test.kintura.com, and now when I try to create "mydomain.com" on cpdemo.kintura.com, I get "The hostname has already been taken."

**Comment by kintura** [comment]
It is by design.  Also now wondering if we should put some dns TEXT domain ownership verification before they're allowed to.
