### ISSUE TITLE
For cids that have multiple offer conversions, the conversions only register on the first offer converted

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#10]
Should multiple offers be able to convert on the same cid?

If yes, then the following flow produces invalid click data:
https://test.kintura.io/in/[campaign]
https://test.kintura.io/out  => goes to offer A
https://test.kintura.io/conversion?cid=[cid]
https://test.kintura.io/out  => goes to offer B
https://test.kintura.io/conversion?cid=[cid]  => same cid as previous conversion
https://test.kintura.io/utilities/cid/[cid] => will show 2 conversions on offer A and none on B, as opposed to one version for A and one for B.

**Comment by kintura** [comment]
cid events are consolidated incorrectly here.  Fixing this.
