### ISSUE TITLE
click data's payout is not additive for multiple conversion requests

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#11]
Should multiple conversion requests on the same offer increase the payout each time? The number of conversions in the click data increases each time, so seems like the payout should to. 

If so, the following results in invalid click data:
https://test.kintura.io/in/FAogwlBvSyOHMf0QuNZF
https://test.kintura.io/out
https://test.kintura.io/conversion?cid=ah9WVFjIaje2rrMo6R0O&payout=12.54&txid=
https://test.kintura.io/conversion?cid=ah9WVFjIaje2rrMo6R0O&payout=1.31&txid=
https://test.kintura.io/utilities/cid/ah9WVFjIaje2rrMo6R0O

Click data should show payout of 12.54 + 1.31, but it only shows a payout of 12.54.

**Comment by kintura** [comment]
For sure.  In fact, this is related to #10 -- the issue here is directly tied to how duplicates are determined and the special rules for conversions need to be put in place.

**Comment by spunkychrispi** [comment]
Ah, I just figured out that changing the "txid" creates a new conversion in the events. Perhaps if it doesn't have a new transaction id then it's a duplicate conversion.

**Comment by kintura** [comment]
Yeah txid should be a *new* event there.  Really "count" shouldn't be applied to the conversion log in utilities/cid

**Comment by kintura** [comment]
Deploying this fix in a couple hours.

**Comment by spunkychrispi** [comment]
Confirmed fixed. Each conversion always shows as a separate event now, so never any need to add payouts together.
