### ISSUE TITLE
requesting landing => offer => conversion flow multiple times sometimes fails

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#12]
https://test.kintura.io/in/FAogwlBvSyOHMf0QuNZF
https://test.kintura.io/out
https://test.kintura.io/conversion?cid=[cid]

Running this request multiple times sometimes results in conversion returning the "campaign not found" error. When this occurs it is usually prefaced by the landing request that hangs for a number of seconds. Then even if there is a wait of 10 seconds between the landing and the offer request, the conversion request will still fail. 

A test for this can be found in stress.test.js.

**Comment by spunkychrispi** [comment]
Covered in stress.test.js

**Comment by kintura** [comment]
Not seeing stress.test.js in master branch.

**Comment by kintura** [comment]
https://github.com/kintura/qa/blob/ap-stress/test/stress.test.js#L25 I was able to get it to run smoothly with a 2 second delay between offer and conversion.  For stress testing itself it might be better to run requests in parallel.  What's weird to me is the delay from landing.
