### ISSUE TITLE
Cannot enable offer conversion cap because timezone search does not complete

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#15]
When trying to enable the conversion cap on an offer, the search on the timezone field hangs so that a timezone can not be selected and the conversion cap cannot be saved. 

The timezone (http://test.kintura.io/1.0/time_zones?search=pacific) search returns with a 400:

error: "Sorry, something went wrong."
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
message: "Class 'App\ELoquent\Region' not found"

**Comment by kintura** [comment]
Yikes.  Fixed.
