### ISSUE TITLE
save button does not re-enable when trying to save new offer

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#2]
Text fields are working properly: The text fields validate on the client, so if you click Save without filling out any fields, the text fields will throw validation errors and the Save button will be disabled. If you then go and fill out the required text fields, the Save button will re-enable again. 

However, the Affiliate Network dropdown does not validate on the client like the text fields do, so if you save the form without first selecting an Affiliate Network, the Save button will disable and "Please correct all invalid fields" will display, but there is no validate error below the Affiliate Network dropdown, indicating that it is a required field, and if you select a value for it, the Save button does not re-enable. So you essentially cannot save the offer.

**Comment by kintura** [comment]
Fixed but still need to improve SelectOrCreate().  Noted in console repo https://github.com/kintura/kin-console-vue/issues/5
