### ISSUE TITLE
Time of Date filter: not clear on what timezone is used. 

### ISSUE THREAD

**Issue by spunkychrispi** [kintura/qa#24]
This feature is perhaps unusable as is because it's not clear what timezone the time settings are referring to. 

![screen shot 2018-09-03 at 9 05 44 am](https://user-images.githubusercontent.com/14365633/44991067-9e24e100-af58-11e8-9471-8dc263376b99.jpg)

**Comment by kintura** [comment]
I wonder if it should be described better.  It's the time of day for the end-user.

**Comment by spunkychrispi** [comment]
Ah, okay that makes sense then. Perhaps just some additional description.
